language: ruby
cache: bundler
rvm:
- 2.1.5
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
